server:
  port: 8080
spring:
  application:
    name: "natural-person-transaction-payments"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
  jackson:
    serialization:
      write-dates-as-timestamps: false
  profiles:
    include: null
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: "http://localhost:3000/static/jwks.json"
          issuer: "reusos-scaffold"
          subject: "natural-person-payment"
  redis:
    host: "localhost"
    port: 6379
    password: your_secure_password
commons:
  jms:
    input-concurrency: 10
    input-queue: "DEV.QUEUE.1"
    input-queue-alias: ""
    reactive: true
    output-concurrency: 10
    output-queue: "DEV.QUEUE.2"
    producer-ttl: 0
ibm:
  mq:
    conn-name: "127.0.0.1(1414)"
    channel: "DEV.APP.SVRCONN"
    user: "app"
    password: "passw0rd"
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
  health:
    circuitbreakers:
      enabled: true
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"
adapter:
  restconsumer:
    timeout: 5000
    natural-person-data-url: "http://localhost:3002"
    natural-person-account-url: "http://localhost:3001"
resilience4j:
  circuitbreaker:
    instances:
      testGet:
        registerHealthIndicator: true
        failureRateThreshold: 50
        slowCallRateThreshold: 50
        slowCallDurationThreshold: "2s"
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        minimumNumberOfCalls: 10
        waitDurationInOpenState: "10s"
      testPost:
        registerHealthIndicator: true
        failureRateThreshold: 50
        slowCallRateThreshold: 50
        slowCallDurationThreshold: "2s"
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        minimumNumberOfCalls: 10
        waitDurationInOpenState: "10s"
logging:
  level:
    org.springframework.security: "DEBUG"
jwt-config:
  issuer: "reusos-scaffold"
  kid: "reusos-scaffold-tutorial"
  private-key-path: "classpath:private-key.pem"
  expiration-seconds: 60
